//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entity.Authority
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuthorityContainer : DbContext
    {
        public AuthorityContainer()
            : base("name=AuthorityContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Authority> Authority { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<File> File { get; set; }
        public virtual DbSet<PageElement> PageElement { get; set; }
        public virtual DbSet<Action> Action { get; set; }
    }
}
