//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Mobile {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Mobile.MobileWebServiceSoap")]
    public interface MobileWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 data 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcuteService", ReplyAction="*")]
        ConsoleApp1.Mobile.ExcuteServiceResponse ExcuteService(ConsoleApp1.Mobile.ExcuteServiceRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 data 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExcuteServiceForCom", ReplyAction="*")]
        ConsoleApp1.Mobile.ExcuteServiceForComResponse ExcuteServiceForCom(ConsoleApp1.Mobile.ExcuteServiceForComRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcuteServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExcuteService", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.Mobile.ExcuteServiceRequestBody Body;
        
        public ExcuteServiceRequest() {
        }
        
        public ExcuteServiceRequest(ConsoleApp1.Mobile.ExcuteServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExcuteServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] data;
        
        public ExcuteServiceRequestBody() {
        }
        
        public ExcuteServiceRequestBody(byte[] data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcuteServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExcuteServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.Mobile.ExcuteServiceResponseBody Body;
        
        public ExcuteServiceResponse() {
        }
        
        public ExcuteServiceResponse(ConsoleApp1.Mobile.ExcuteServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExcuteServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ExcuteServiceResult;
        
        public ExcuteServiceResponseBody() {
        }
        
        public ExcuteServiceResponseBody(byte[] ExcuteServiceResult) {
            this.ExcuteServiceResult = ExcuteServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcuteServiceForComRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExcuteServiceForCom", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.Mobile.ExcuteServiceForComRequestBody Body;
        
        public ExcuteServiceForComRequest() {
        }
        
        public ExcuteServiceForComRequest(ConsoleApp1.Mobile.ExcuteServiceForComRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExcuteServiceForComRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] data;
        
        public ExcuteServiceForComRequestBody() {
        }
        
        public ExcuteServiceForComRequestBody(byte[] data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExcuteServiceForComResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExcuteServiceForComResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.Mobile.ExcuteServiceForComResponseBody Body;
        
        public ExcuteServiceForComResponse() {
        }
        
        public ExcuteServiceForComResponse(ConsoleApp1.Mobile.ExcuteServiceForComResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExcuteServiceForComResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ExcuteServiceForComResult;
        
        public ExcuteServiceForComResponseBody() {
        }
        
        public ExcuteServiceForComResponseBody(byte[] ExcuteServiceForComResult) {
            this.ExcuteServiceForComResult = ExcuteServiceForComResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MobileWebServiceSoapChannel : ConsoleApp1.Mobile.MobileWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobileWebServiceSoapClient : System.ServiceModel.ClientBase<ConsoleApp1.Mobile.MobileWebServiceSoap>, ConsoleApp1.Mobile.MobileWebServiceSoap {
        
        public MobileWebServiceSoapClient() {
        }
        
        public MobileWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobileWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.Mobile.ExcuteServiceResponse ConsoleApp1.Mobile.MobileWebServiceSoap.ExcuteService(ConsoleApp1.Mobile.ExcuteServiceRequest request) {
            return base.Channel.ExcuteService(request);
        }
        
        public byte[] ExcuteService(byte[] data) {
            ConsoleApp1.Mobile.ExcuteServiceRequest inValue = new ConsoleApp1.Mobile.ExcuteServiceRequest();
            inValue.Body = new ConsoleApp1.Mobile.ExcuteServiceRequestBody();
            inValue.Body.data = data;
            ConsoleApp1.Mobile.ExcuteServiceResponse retVal = ((ConsoleApp1.Mobile.MobileWebServiceSoap)(this)).ExcuteService(inValue);
            return retVal.Body.ExcuteServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.Mobile.ExcuteServiceForComResponse ConsoleApp1.Mobile.MobileWebServiceSoap.ExcuteServiceForCom(ConsoleApp1.Mobile.ExcuteServiceForComRequest request) {
            return base.Channel.ExcuteServiceForCom(request);
        }
        
        public byte[] ExcuteServiceForCom(byte[] data) {
            ConsoleApp1.Mobile.ExcuteServiceForComRequest inValue = new ConsoleApp1.Mobile.ExcuteServiceForComRequest();
            inValue.Body = new ConsoleApp1.Mobile.ExcuteServiceForComRequestBody();
            inValue.Body.data = data;
            ConsoleApp1.Mobile.ExcuteServiceForComResponse retVal = ((ConsoleApp1.Mobile.MobileWebServiceSoap)(this)).ExcuteServiceForCom(inValue);
            return retVal.Body.ExcuteServiceForComResult;
        }
    }
}
