//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IProductMoveService")]
    public interface IProductMoveService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductMoveService/DoMove", ReplyAction="http://tempuri.org/IProductMoveService/DoMoveResponse")]
        string DoMove(string[] list, string targetLocalPID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductMoveServiceChannel : ConsoleApp1.ServiceReference.IProductMoveService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductMoveServiceClient : System.ServiceModel.ClientBase<ConsoleApp1.ServiceReference.IProductMoveService>, ConsoleApp1.ServiceReference.IProductMoveService {
        
        public ProductMoveServiceClient() {
        }
        
        public ProductMoveServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductMoveServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductMoveServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductMoveServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoMove(string[] list, string targetLocalPID) {
            return base.Channel.DoMove(list, targetLocalPID);
        }
    }
}
